/*
 * Copyright 2026 Ross Haugh
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.orhaugh.chord.jdbc;

import io.github.orhaugh.chord.ChordException;
import io.github.orhaugh.chord.client.NativeConnection;
import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.time.Duration;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 * A JDBC connection over one CHord native connection.
 *
 * <p>ClickHouse has no classic transactions: the connection is permanently in auto commit and
 * {@code setAutoCommit(false)}, savepoints and rollback raise honest errors. One statement may
 * stream at a time, matching the native protocol's one exchange per connection rule; JDBC objects
 * created by this connection are not thread safe.
 */
final class ChordConnection implements Connection {

  private final NativeConnection connection;
  private final String database;
  private final Duration defaultQueryTimeout;
  private volatile boolean closed;

  ChordConnection(NativeConnection connection, String database, Duration defaultQueryTimeout) {
    this.connection = connection;
    this.database = database;
    this.defaultQueryTimeout = defaultQueryTimeout;
  }

  NativeConnection nativeConnection() {
    return connection;
  }

  Duration defaultQueryTimeout() {
    return defaultQueryTimeout;
  }

  private void ensureOpen() throws SQLException {
    if (closed) {
      throw SqlExceptions.closed("connection");
    }
  }

  @Override
  public Statement createStatement() throws SQLException {
    ensureOpen();
    return new ChordStatement(this);
  }

  @Override
  public Statement createStatement(int resultSetType, int resultSetConcurrency)
      throws SQLException {
    requireForwardReadOnly(resultSetType, resultSetConcurrency);
    return createStatement();
  }

  @Override
  public Statement createStatement(
      int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
    requireForwardReadOnly(resultSetType, resultSetConcurrency);
    return createStatement();
  }

  @Override
  public PreparedStatement prepareStatement(String sql) throws SQLException {
    ensureOpen();
    return new ChordPreparedStatement(this, sql);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
      throws SQLException {
    requireForwardReadOnly(resultSetType, resultSetConcurrency);
    return prepareStatement(sql);
  }

  @Override
  public PreparedStatement prepareStatement(
      String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
      throws SQLException {
    requireForwardReadOnly(resultSetType, resultSetConcurrency);
    return prepareStatement(sql);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
    if (autoGeneratedKeys != Statement.NO_GENERATED_KEYS) {
      throw SqlExceptions.unsupported("Generated keys");
    }
    return prepareStatement(sql);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
    throw SqlExceptions.unsupported("Generated keys");
  }

  @Override
  public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
    throw SqlExceptions.unsupported("Generated keys");
  }

  private static void requireForwardReadOnly(int resultSetType, int resultSetConcurrency)
      throws SQLException {
    if (resultSetType != ResultSet.TYPE_FORWARD_ONLY
        || resultSetConcurrency != ResultSet.CONCUR_READ_ONLY) {
      throw SqlExceptions.unsupported("Scrollable or updatable result sets");
    }
  }

  @Override
  public CallableStatement prepareCall(String sql) throws SQLException {
    throw SqlExceptions.unsupported("Callable statements");
  }

  @Override
  public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency)
      throws SQLException {
    throw SqlExceptions.unsupported("Callable statements");
  }

  @Override
  public CallableStatement prepareCall(
      String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
      throws SQLException {
    throw SqlExceptions.unsupported("Callable statements");
  }

  @Override
  public String nativeSQL(String sql) {
    return sql;
  }

  @Override
  public void setAutoCommit(boolean autoCommit) throws SQLException {
    ensureOpen();
    if (!autoCommit) {
      throw SqlExceptions.unsupported(
          "Transactions (ClickHouse executes each statement atomically)");
    }
  }

  @Override
  public boolean getAutoCommit() throws SQLException {
    ensureOpen();
    return true;
  }

  @Override
  public void commit() throws SQLException {
    throw new SQLException("The connection is in auto commit mode", "25000");
  }

  @Override
  public void rollback() throws SQLException {
    throw new SQLException("The connection is in auto commit mode", "25000");
  }

  @Override
  public void rollback(Savepoint savepoint) throws SQLException {
    throw SqlExceptions.unsupported("Savepoints");
  }

  @Override
  public Savepoint setSavepoint() throws SQLException {
    throw SqlExceptions.unsupported("Savepoints");
  }

  @Override
  public Savepoint setSavepoint(String name) throws SQLException {
    throw SqlExceptions.unsupported("Savepoints");
  }

  @Override
  public void releaseSavepoint(Savepoint savepoint) throws SQLException {
    throw SqlExceptions.unsupported("Savepoints");
  }

  @Override
  public void close() {
    if (!closed) {
      closed = true;
      connection.close();
    }
  }

  @Override
  public boolean isClosed() {
    return closed;
  }

  @Override
  public boolean isValid(int timeoutSeconds) throws SQLException {
    if (timeoutSeconds < 0) {
      throw new SQLException("timeout must not be negative", "HY000");
    }
    if (closed) {
      return false;
    }
    try {
      connection.ping();
      return true;
    } catch (ChordException e) {
      return false;
    }
  }

  @Override
  public DatabaseMetaData getMetaData() throws SQLException {
    ensureOpen();
    return new ChordDatabaseMetaData(this);
  }

  @Override
  public void setReadOnly(boolean readOnly) throws SQLException {
    ensureOpen();
    // A hint the spec allows drivers to ignore; ClickHouse enforces rights server side.
  }

  @Override
  public boolean isReadOnly() throws SQLException {
    ensureOpen();
    return false;
  }

  @Override
  public void setCatalog(String catalog) throws SQLException {
    ensureOpen();
    if (catalog != null && !catalog.equals(getCatalog())) {
      throw SqlExceptions.unsupported(
          "Switching databases on an open connection (reconnect with the target database)");
    }
  }

  @Override
  public String getCatalog() throws SQLException {
    ensureOpen();
    return database.isEmpty() ? "default" : database;
  }

  @Override
  public void setSchema(String schema) throws SQLException {
    ensureOpen();
    // ClickHouse has a single namespace level, exposed as catalogs; schemas are a no op.
  }

  @Override
  public String getSchema() throws SQLException {
    ensureOpen();
    return null;
  }

  @Override
  public void setTransactionIsolation(int level) throws SQLException {
    ensureOpen();
    if (level != Connection.TRANSACTION_NONE) {
      throw SqlExceptions.unsupported("Transaction isolation levels");
    }
  }

  @Override
  public int getTransactionIsolation() throws SQLException {
    ensureOpen();
    return Connection.TRANSACTION_NONE;
  }

  @Override
  public SQLWarning getWarnings() throws SQLException {
    ensureOpen();
    return null;
  }

  @Override
  public void clearWarnings() throws SQLException {
    ensureOpen();
  }

  @Override
  public Map<String, Class<?>> getTypeMap() throws SQLException {
    ensureOpen();
    return Map.of();
  }

  @Override
  public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
    throw SqlExceptions.unsupported("Custom type maps");
  }

  @Override
  public void setHoldability(int holdability) throws SQLException {
    if (holdability != ResultSet.CLOSE_CURSORS_AT_COMMIT) {
      throw SqlExceptions.unsupported("Holdable cursors");
    }
  }

  @Override
  public int getHoldability() {
    return ResultSet.CLOSE_CURSORS_AT_COMMIT;
  }

  @Override
  public Clob createClob() throws SQLException {
    throw SqlExceptions.unsupported("CLOB values");
  }

  @Override
  public Blob createBlob() throws SQLException {
    throw SqlExceptions.unsupported("BLOB values");
  }

  @Override
  public NClob createNClob() throws SQLException {
    throw SqlExceptions.unsupported("NCLOB values");
  }

  @Override
  public SQLXML createSQLXML() throws SQLException {
    throw SqlExceptions.unsupported("SQLXML values");
  }

  @Override
  public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
    throw SqlExceptions.unsupported("Client created Array objects");
  }

  @Override
  public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
    throw SqlExceptions.unsupported("Struct values");
  }

  @Override
  public void setClientInfo(String name, String value) throws SQLClientInfoException {
    throw new SQLClientInfoException("Client info properties are not supported", Map.of());
  }

  @Override
  public void setClientInfo(Properties properties) throws SQLClientInfoException {
    throw new SQLClientInfoException("Client info properties are not supported", Map.of());
  }

  @Override
  public String getClientInfo(String name) throws SQLException {
    ensureOpen();
    return null;
  }

  @Override
  public Properties getClientInfo() throws SQLException {
    ensureOpen();
    return new Properties();
  }

  @Override
  public void abort(Executor executor) {
    close();
  }

  @Override
  public void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException {
    throw SqlExceptions.unsupported(
        "Changing the network timeout on an open connection (set read_timeout_ms in the URL)");
  }

  @Override
  public int getNetworkTimeout() throws SQLException {
    ensureOpen();
    return 0;
  }

  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException {
    if (iface.isInstance(this)) {
      return iface.cast(this);
    }
    if (iface.isInstance(connection)) {
      return iface.cast(connection);
    }
    throw new SQLException("Cannot unwrap to " + iface.getName(), "HY000");
  }

  @Override
  public boolean isWrapperFor(Class<?> iface) {
    return iface.isInstance(this) || iface.isInstance(connection);
  }
}
